### ISSUE TITLE
Feature: Add Ledger Support for Statemine

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/common#1025]
Ledger plans to release an app for Statemine: https://github.com/zondax/ledger-statemine

Add support to Apps UI to make transactions using a Ledger on Statemine.

**Comment by jacogr** [comment]
Adding the details in `@polkadot/networks` https://github.com/polkadot-js/common/blob/master/packages/networks/src/defaults.ts#L58 probably won't work at all unless we have the hanging PRs below since these don't match through with the `isLedgerCapable` flags (shared details from the registry) -

https://github.com/polkadot-js/apps/pull/5618
https://github.com/polkadot-js/extension/pull/752
