### ISSUE TITLE
Critical regression in isHex

### ISSUE THREAD

**Issue by nazar-pc** [polkadot-js/common#1204]
Regression comes from https://github.com/polkadot-js/common/pull/1184 and is the root cause of https://github.com/polkadot-js/apps/issues/6569

The reason is that `isHex` started using capture groups, which is a much heavier and more expensive mechanism and it is failing with stack overflow completely on long inputs.

Our blockchain is designed to store data and this regression breaks polkadot.js apps UI because it can no longer process block contents.

Attaching an example of such long input string that I had issues with:
[long-input-string.txt](https://github.com/polkadot-js/common/files/7565247/long-input-string.txt)

**Comment by jacogr** [comment]
As a rule, the API and utils focusses on correctness, not performance. It doesn't mean it is not important, just that it is a second priority. In this case the previous logic was incorrect.

In this case there are different ways to determine the length, so the capture group can be removed - and it indeed does seem to parse the problematic block once removed and the length checks adjusted. Why it ends up with a recursion issue is beyond my understanding, stack depth !== speed.

PS: Very good bisect to point to the root cause.
