### ISSUE TITLE
mnemonicGenerate is undefined on React Native (expo 5.0.3)

### ISSUE THREAD

**Issue by jbowa** [polkadot-js/common#1422]
Hey,

I managed to install the latest version of`@polkadot/util-crypto` on React Native (expo) using `npm`.

when I import the package uisng `import { mnemonicGenerate } from '@polkadot/util-crypto'`

`mnemonicGenerate` is undefined. To support `CommonJS` I had to add `metro.config.js` and the following code:

```JavaScript
const { getDefaultConfig } = require('@expo/metro-config');

const defaultConfig = getDefaultConfig(__dirname);

defaultConfig.resolver.assetExts.push('cjs');

module.exports = defaultConfig;
```

**Comment by jacogr** [comment]
All packages expose both ESM and CJS via export maps. Weird that Expo chooses to use the CJS version, but good that you have a configuration that works for you.

**Comment by jbowa** [comment]
Hey @jacogr thanks for the quick reply. I was able to get it to build without complaining but the issue is still there. [Here](https://github.com/jbowa/rn-test-app/blob/main/App.tsx) is an example with the react native create app script. Uncommenting

```JavaScript
const seed = mnemonicGenerate();
```
throws

```
Cannot use 'import.meta' outside a module. 
```

**Comment by jacogr** [comment]
8.5.1 only has a workaround for Vite where it turns import.meta into undefined in productions builds. (Which then subsequently makes the usage thereof in “new URL(…)” fail)

The issue here seems that Expo treats the JS files as CJS instead of ESM and then complains about the usage of import.meta. (Basically it ignores the export maps in the package.json completely)

**Comment by jacogr** [comment]
Ok, this is how I would debug this (since stack-traces are a luxury here). This is on a duplicate project, here just using minimal dependencies.

### step 1

Figure out if Expo/Metro/whatever handles the main/module correctly with no issues.

```js
import { packageInfo, xglobal } from '@polkadot/x-global';

// interested if the type field here is esm or cjs (that will show what Expo does)
console.log('packageInfo=', JSON.stringify(packageInfo));

// this should hopefully work, only main & module fields in the package.json
console.log('xglobal=', xglobal);
```

### step 2

Assuming the above passes, we turn up the heat with a package.json that does have a react-native entry as well. (If this fails, continue to step 3, if this passes... well, that would be weird)

```js
import { getRandomValues, packageInfo } from '@polkadot/x-randomvalues';

 // interested if the type field here is esm or cjs (that will show what Expo does)
console.log('packageInfo=', JSON.stringify(packageInfo));

// see if this works, i.e. should be something
console.log('getRandomValues=', getRandomValues(new Uint8Array(5)));
```

### step 3

Now we see if RN actually can work with the `react-native` field in the export map only or if it needs the `react-native` key (this key points to ESM). 

(a) First we open `node_modules/@polkadot/x-randomvalues/package.json` and remove the `react-native` as well as `browser` fields (those top-level, not under the exports key)

(b) Repeat the test above

### addendum 

I'm saying this is how "I would debug this" but since I cannot for the life of me get a RN environment setup (despite best efforts), help would be appreciated.

**Comment by Tbaut** [comment]
Thanks a lot Jaco for the super thorough instructions.
I tried on a freshly created expo project

- step 1 worked 
```
packageInfo= {"name":"@polkadot/x-global","path":"auto","type":"cjs","version":"8.5.1"}
xglobal= [Object]
```
Note here that I couldn't show the xglobal, because it's a "cyclic structure" and JSON.stringify wasn't happy with it.

- step 2 failed as expected with the "import.meta only valid inside modules". There's a java stack but it's useless I believe
![image](https://user-images.githubusercontent.com/33178835/158410155-966e94a3-cd49-41af-ad44-2233bc1bfd75.png)

- step 3, removed the react-native and browser top level, and run the project (from step 2)
Getting the following error:
```
Android Bundling failed 4731ms
Unable to resolve module crypto from /home/thib/TestProject/node_modules/@polkadot/x-randomvalues/node.cjs: crypto could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  14 | });
  15 |
> 16 | var _crypto = _interopRequireDefault(require("crypto"));
     |                                               ^
  17 |
  18 | var _packageInfo = require("./packageInfo.cjs");
  19 |
```

**Comment by jacogr** [comment]
Perfect! That helps. Ok, so basically it tells me that Expo is going for the CJS version, this makes sense. Removing the stuff in step 3 the falls back to the package `main` which is certainly not what we want here.

So something to try - instead of removing the `react-native` field, change it to `"react-native": "./react-native.cjs"` (I would love to try `"react-native": "./react-native" here as well, the second form is certainly preferable... and will work if Expo tries to navigate through export maps as well)

If you don't have the originals, here are the removed fields (copied from a build output) -

```
  "main": "node.cjs",
  "module": "node.js",
  "browser": "browser.js",
  "react-native": "react-native.js",
```

**Comment by Tbaut** [comment]
Nice, with:
- `"react-native": "react-native.cjs"` I get
```
packageInfo= {"name":"@polkadot/x-randomvalues","path":"auto","type":"cjs","version":"8.5.1"}

TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNGetRandomValues.getRandomBase64')
at node_modules/@polkadot/x-randomvalues/react-native.cjs:31:39 in getRandomValuesNative
```
![image](https://user-images.githubusercontent.com/33178835/158428536-f9c7e249-a964-47b6-a299-8c1c889fd3e6.png)

- `"react-native": "./react-native"` I get the import.meta issue again (note that there's actually no react-native dir in the `x-randomvalues`

**Comment by jacogr** [comment]
This is weird - `TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNGetRandomValues.getRandomBase64')
at node_modules/@polkadot/x-randomvalues/react-native.cjs:31:39 in getRandomValuesNative` (but a different issue)

Ok, so I can adjust the build outputs for all to point to the `.cjs` file everywhere.

**Comment by jacogr** [comment]
`8.5.2-4` has the changes with pointing the `react-native` entry to CJS-only. A test would be appreciated to see if that moves in the right direction.

PS: I'm acutely aware that you should not (a) use users as a debugger & (b) use users as testers, but alas... in this case...

**Comment by Tbaut** [comment]
No problem at all, that's the least we can do, thank you so much for this, I tested the `"8.5.2-4` you nailed it!

```
packageInfo= {"name":"@polkadot/x-randomvalues","path":"auto","type":"cjs","version":"8.5.2-4"}
getRandomValues= Uint8Array [
  84,
  92,
  74,
  197,
  135,
]

```

**Comment by jacogr** [comment]
Great. I’ll try to do more reading as to the “why” here. This doesn’t make sense at all.

**Comment by jbowa** [comment]
@Tbaut @jacogr Thanks gents! this looks good on my end. @jacogr close it?

**Comment by jacogr** [comment]
It will be contained in the stable release tomorrow.
