### ISSUE TITLE
Hash of https://esm.sh/@noble/curves@1.1.0/ed25519.js often change

### ISSUE THREAD

**Issue by jasl** [polkadot-js/common#1852]
This is an issue report for polkadot.js@Deno

I'm using `deno cache --reload ./main.ts` to cache dependencies for my Deno app,
after maybe a week, rerun the command, it may get the error

```
error: The source code is invalid, as it does not match the expected hash in the lock file.KiB/210.59KiB (1561/1562)
  Specifier: https://esm.sh/@noble/curves@1.1.0/ed25519.js
```

**Comment by jacogr** [comment]
This is most probably due to an esm.sh version upgrade. 

We don’t control that infrastructure.

**Comment by jasl** [comment]
Yeah, does this lib controlled by you?
only this lib hash often change which really odd...

**Comment by jacogr** [comment]
Nope. 

Noble is a different package. (And the published version certainly does not change)

The Polkadot-JS deno version uses that via esm.sh. 

At some point it will swap to not using esm.sh but until Deno correctly supports npm: namespaces (which includes npm git deps as well), it cannot be swapped over.

**Comment by jasl** [comment]
Ok, thank for clarify

**Comment by jacogr** [comment]
It is most certainly due to an esm.sh version bump. If you load the file from the link you supplied in the browser, this is what is shows -

/* esm.sh - @noble/curves@1.1.0/ed25519 */
export * from "https://esm.sh/v126/@noble/curves@1.1.0/es2015/ed25519.js";

So esm.sh adds their version as to when it was built.
