### ISSUE TITLE
Bring isTestChain into common/util

### ISSUE THREAD

**Issue by yjkimjunior** [polkadot-js/common#319]
As brought up by @Stefie, this utility function is being used in both `polkadot-js/apps` and `paritytech/substrate-light-ui` so probably ought to pulled out to `common`

**Comment by jacogr** [comment]
Duplicate of https://github.com/polkadot-js/apps (implemented in https://github.com/polkadot-js/ui/pull/76)

The rationale for pulling those in there is that especially around formatting, there is a dependency on `@polkadot/types` which sits on a higher-level. Not 100% on the naming of `ui-util`, but since there is a `api` repo dep in there with additional utils, it makes more sense at a higher level.

Want to keep chain-specific stuff out of this repo rather.
