### ISSUE TITLE
A question on util-crypto/nacl's deriveHard() usage

### ISSUE THREAD

**Issue by hskang9** [polkadot-js/common#399]
As far as I know,

in [SLIP-0010](https://github.com/satoshilabs/slips/blob/master/slip-0010.md), deriving child key on ed25519 curve means:
1. create hmac of key and chaincode
2. slice first 32 byte (IL) as key(the seed to generate new key), and the other 32 byte (IR) for chaincode to make entropy in next generation of keys.

but `util-crypto/nacl`'s `deriveHard()` generates blake2 hash of concatenated(master_secret('ed25519 seed'), IL, IR). 

Is there a missing component in the key derivation?

**Comment by jacogr** [comment]
This maps to what is done in substrate/polkadot, i.e. https://github.com/paritytech/substrate/blob/master/core/primitives/src/ed25519.rs#L334-L340

At launch, the default pairs will be sr25519 (for general accounts, i.e. https://github.com/w3f/schnorrkel) and TBD for sessions (currently the only place ed25519 generally should be used at,)

**Comment by hskang9** [comment]
Will sr25519 lib be used asynchronously due to the fact that wasm has to be compiled asynchronously or will it be synchronous by porting sr25519 in javascript or update when wasm can be compiled synchronously?

**Comment by jacogr** [comment]
Currently the WASM is instantiated in an async manner. (Not pretty since it "hacks around" the Rust wasm-pack somewhat - https://github.com/polkadot-js/wasm/blob/master/scripts/build-package.sh#L76. Build process used wasm-pack to build and then adjusts the outputs for async and some other polyfills). 

In a Node.js env sync works really well, however in browser webpack environments the sync init does not work as well, or rather results in something that doesn't work and throws warnings.

For all the functions exposed in that repo, there are JS fallbacks, e.g. ed25519 or blake2, etc. (when the WASM is not instantiated yet), however there is nothing like that for sr25519. Atm there are no plans to port this to JS - would love a JS implementation, however prefer not doing crypto code myself and leave it yo people who work with thius stuff the whole day.

(As an aside there has been some playing with an asm.js fallback version, however it just bloats the packages completely to >13MB, so effectively if you don't have a WASM-capable env. at present, there is no sr25519 support at all)

**Comment by hskang9** [comment]
I agree that wasm for now is really tricky, and I heard that they are working on synchronous compilation this year. Okay working on js implementation starting now. I hope if there is a bounty on this.

**Comment by jacogr** [comment]
@hskang9 I would suggest contacting the W3F for a couple of reasons -

- they did the w3f/schnorrkel and worst-case can get you in touch with the guy behind that
- they may very well be open for the suggestion of a port + bounty on the port

**Comment by hskang9** [comment]
@jacogr  Thank you! I have already sent burdges in w3f for my plan to work on this, but here are two plans to share the suggestion that I have thought.

1. w3f/schnorrkel is based on `curve25519-dalek` from [Ristretto Group](https://ristretto.group/implementations.html), and I found a C implementation. I am thinking to make Js wrapper of that C library and build schnorrkel great again with js.

2. Configure some constants in existing ed25519 js lib. After I investigated and asked Mr.Burdges, I found out that the curve is same between ed25519 and sr25519 hopefully, so I think this is probably the easiest one if I can just apply the corresponding configuration there(e.g. cofactor of 8).

**Comment by jacogr** [comment]
The C wrapper is fine, but doesn’t really help in a RN or browser environment, only in a Node.js env. 

And yes, Jeff is the right person from a technical POV. (Obviously:))

**Comment by hskang9** [comment]
I think I would have to add ristretto group layer to use it with ed25519's key in Extended key type to make sr25519.

I will get confirm from him in a day or tmrw.

**Comment by jacogr** [comment]
Really looking forward to playing with whatever you come up with. (Like I mentioned earlier, not something I would attempt myself since I'm no immersed enough in the crypto world, and well, idiots shouldn't do crypto, but would love a JS impl)

**Comment by jiangfuyao** [comment]
> The C wrapper is fine, but doesn’t really help in a RN or browser environment, only in a Node.js env.
> 
> And yes, Jeff is the right person from a technical POV. (Obviously:))

The Hardware wallet need C or C++ sr25519 lib.

**Comment by jiangfuyao** [comment]
@hskang9 
C language implementation.
https://github.com/Warchant/sr25519-crust

https://travis-ci.org/Warchant/sr25519-crust

**Comment by hskang9** [comment]
@jacogr don't just discourage yourself, there must be something that we can do together. I will post the repo for that here. @jiangfuyao Thank you for introducing wrapper interface, I should look into that and use it to build js wrapper, but I think I will first make ristretto point layer to feed as a seed in x25519 algorithm. After I tweaked around the code, it looks like sr25519 consists of 
```
seed -> ristretto point serialized as 32 bytes for key property in x25519 extended key -> sr keypair
```
I am excited as well to build this layer for sr25519.

**Comment by jacogr** [comment]
Closing this one. Happy as it stands with the WASM bridge.
