### ISSUE TITLE
Support for Ethereum compatible ECDSA 

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/common#656]
Current ECDSA configuration in the PolkadotJS is using Blake2 Hash into H256 (which is also the setup for Substrate default ECDSA)

In order to support Ethereum compatible chains (Like https://github.com/paritytech/frontier pallet offers), it needs to have a Eth compatible implementation of the ECDSA using Keccak256 into H160 Account ID.
This would also require to skip the base58 encoding (as Eth addresses are not commonly using base58)

I think in order to maintain current ECDSA, it would be good to include a forth type: `ecdsa-eth` (others being "sr25519", "ed25519", "ecdsa"), but I'm open to other solutions.

Most of the changes to support it needs to be done in the @polkadot/util-crypto/address and @polkadot/keyring

**Comment by jacogr** [comment]
ECDSA support was added in https://github.com/polkadot-js/common/pull/589 - the reason for linking that is that the support would be exactly the same in terms or areas touched and tests added. (Also a good example since the first two were done over time and alongside each-other) 

Here there are some shortcuts which can be taken, since this deals with mostly hashing changes a lot of the functions (added above) can just be extended with an additional param that specified the hash type, for example 

`secp256k1Sign (message: Uint8Array | string, { secretKey }: Partial<Keypair>)`

becomes

`secp256k1Sign (message: Uint8Array | string, { secretKey }: Partial<Keypair>, hasher = 'blake2' | 'keccak')`

(Alongside adjustment of tests and the addition of new)

Overall def. something to consider as a new `ethereum` keypair.

**Comment by crystalin** [comment]
Thank you @jacogr , that sounds good.
Is it something your team has time to work on ?
I can probably try to come with a PR but not being familiar with your code, it will take me more time.

**Comment by jacogr** [comment]
PRs are always preferred and welcome. Since the polkadot-js team is effectively me on all the repos hosted here, I do rely on contributions for non-as-shipped-core a lot. I do get to everything, but no promises as to "when".

**Comment by crystalin** [comment]
Oh, you have done a lot of work on it already. Thanks
I believe this will be directly usable once the #661 is merged as it includes the "ethereum" type.
Let me know if you want me to test the branch

**Comment by crystalin** [comment]
Good work on those PR Jaco !
I've spotted another place where the address doesn't get converted correctly:
https://github.com/polkadot-js/api/blob/c9921f002f8a1dd7aabc0acea31141f60a671c8b/packages/types/src/extrinsic/v4/ExtrinsicSignature.ts#L145

**Comment by jacogr** [comment]
Closing
