### ISSUE TITLE
QUESTION: Is it possible that the logger console.log output is somehow silenced?

### ISSUE THREAD

**Issue by woss** [polkadot-js/common#683]
Hi, i'm wondering is this possible to make it optional?

https://github.com/polkadot-js/common/blob/94dc2d76b3bde8e526be2d3410ef715ec8ac99ed/packages/util/src/logger.ts#L78

when i have the api in tests ( not mocked ) it really messing up the output. 

Probably there is a way to mock the api altogether when it is called from withing the custom wrapper functions but that is yet to be discovered :)

**Comment by jacogr** [comment]
Sadly not. I won't be a nightmare to enhance with that functionality, just has not been done.

**Comment by woss** [comment]
@jacogr thanks for the answer.  when i have time I'll look into it and how it can be done. if you don't mind sending me here links where i should start

**Comment by jacogr** [comment]
PRs would be greatly appreciated!

The logger is here - https://github.com/polkadot-js/common/blob/master/packages/util/src/logger.ts

I think the simplest would probably be to add something on the logger so you can just set it globally to silence. (Would then apply to all)

**Comment by woss** [comment]
one of the *universally* accepted non blocking and env based debug loggers https://www.npmjs.com/package/debug  

I have implemented it in my projects and it works really good. so basically how it works is if you don't set the correct env name in the `DEBUG` var nothing will be shown but if you do then the logs will be shown in that scope. 

like `export ENV=polkadot-js:*` would show ALL the logger output ( given that logger is declared under that namespace) or  `export ENV=polkadot-js:api:*`  would show only api part

i think i should have time to give you something this week, any suggestions on the branch naming of my fork?

**Comment by jacogr** [comment]
`woss-fix-logger` would work :)

In all seriousness, yes, aware of `debug` specifically didn't want to have that granularity initially because that makes everybody have to refer to the code since nobody ever remembers what these things are called. (First hand-experience with the Js client and libp2p which is even more granular than the polkadot-js stuff, just proved that point.) 

For instance when speaking about the API, there is API, RPC (multiple types, the really noisy one in test), codec-related, etc. So in general more happy with "less" that almost acts as a global hammer. 

With that in mind, the `NODE_ENV=test` was an exceptionally poor choice...

**Comment by woss** [comment]
i agree that too much granularity is a bad approach. I personally don't want to know every possible debug component namespace. but let's say that we make a 1-2 namespaces and use that? For kind of bigger components.
