### ISSUE TITLE
Broken links and no documentation

### ISSUE THREAD

**Issue by qalqi** [polkadot-js/common#685]
No documentation is provided at all for packages
https://polkadot.js.org/common/

Also, links mentioned are broken

https://polkadot.js.org/common/keyring/SUMMARY.html
https://polkadot.js.org/common/util-crypto/SUMMARY.html
https://polkadot.js.org/common/keyring/#utilities

**Comment by jacogr** [comment]
It is know, yes, Cannot get to everything, however PRs always welcome.

**Comment by qalqi** [comment]
Please keep the issue open so that somebody/I can contribute.

**Comment by jacogr** [comment]
The reason for closing is because of #671 - the plan is to combine _all_ of the library documentation since we have overlaps and move to a single documentation area. It is too scattered and things like "broken links" just cannot actually be addressed in the current setup at all since part of it is auto-generated and part of it is human generated. (Which also means that READMEs are mostly unusable)

Despite being logged here, the above issue covers the wasm, util, api & ui repos since they are all affected.
