### ISSUE TITLE
Backup file contains address with hex format for ECDSA crypto type

### ISSUE THREAD

**Issue by stepanLav** [polkadot-js/common#688]
**Environment:**
Parity Polkadot v0.8.23-d327000a
api v1.34.0-beta.9
apps v0.59.0-beta.14

**Detail description:**
Backup file contains address with hex format if account create with ECDSA crypto type. 

*Scenario:*

1. Go to accounts tab
2. Click [+Add account]
3. Derive required field, crypto type set ECDSA
4. Click [Next]
5. Click [Save]

**Actual result:**
After account creation - backup json is loaded, into the file "address" as hex format.
<details>
  <summary>For example</summary>
{"address":"0x03968a09fbf17e457bff4b93261a3955f54ffe8a99b996b5116847617c3bdc13b4","encoded":"prCnDs/+g+/Nj6xIbqttgqZmCBNKCVV/wTLXzGuAvGkAgAAAAQAAAAgAAADakOLolY9EDDbzeQKVg7eoqPETHLk9PHY5fyLedaufevLKjWn4DVYAle4SIrA62+qdBHVyqxfZ4/xCmRgACUJNDi7Rvrqj6ho8HQ6nJUEuxnFRJ8BZ6Lkoe7oQ8ycw5KfctW5UIacGVtGFMbaBCpsWsxnZW3K3TwYyrwcmxgY=","encoding":{"content":["pkcs8","ecdsa"],"type":["scrypt","xsalsa20-poly1305"],"version":"3"},"meta":{"genesisHash":"0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe","name":"new","tags":[],"whenCreated":1600432088600}}
</details>

**Expected result:**
Address has encoded in base58 like for other crypto type

**Comment by antonkhvorov** [comment]
> It is by design, as expected. The address field is mean to convey the full publicKey, in address format is is hashed and doesn't reflect the full 65 bytes of an expanded publicKey.

@jacogr I see. I have following questions/suggestions to that
1) Maybe it is reasonable to name this field "publicKey" then and make it consistent across all crypto types? 
2) Or add in addition real "address" field which represents account's address in the network from which account is imported?
3) What is the use case having publicKey decrypted and having it in "address" field (since it can be extracted from "encoded" field)?
4) In Fearless Wallet we want to support Recovery JSON format, and we were relying on "address" field to represent the account address, but it seems that its only representing account address in case of sr25519 and ed25519, and in case of ecdsa we cannot rely on that field, so what we should use for matching accoung from JSON and network?

**Comment by jacogr** [comment]
1. As discussed elsewhere, this will come with the v4 format (v3 sadly had to go quick so it didn't get all the bells whistles planned). And finally fully ed, sr, ecdsa & ecdsa-ethereum forced the hand to revert address to the original hex-only format. So what will happen with v4 is only the hex.

2. Since the pair is only meant for introspection, the address certainly does not convey network information. There is a `genesisHash` field in the metadata if it is tied to a specific network.

3. The whole format is only there for support of the keyring, so the keyring uses it in initial add before unlocked.

4. You should rather just add it to the keyring (or just `createFromJSON` in the latest betas to extract without adding) and it will be a pair for inspection.

**Comment by antonkhvorov** [comment]
> 1. As discussed elsewhere, this will come with the v4 format (v3 sadly had to go quick so it didn't get all the bells whistles planned). And finally fully ed, sr, ecdsa & ecdsa-ethereum forced the hand to revert address to the original hex-only format. So what will happen with v4 is only the hex.
> 2. Since the pair is only meant for introspection, the address certainly does not convey network information. There is a `genesisHash` field in the metadata if it is tied to a specific network.
> 3. The whole format is only there for support of the keyring, so the keyring uses it in initial add before unlocked.
> 4. You should rather just add it to the keyring (or just `createFromJSON` in the latest betas to extract without adding) and it will be a pair for inspection.

Thanks for addressing that list! 
I think for now for v3 JSONs we will have logic to identify network by genesis hash.

And last one -- are there any dates (and maybe format drafts) of v4 Recovery JSON to go live?

**Comment by jacogr** [comment]
It is 3rd on broader the list of priorities, so it is when I finally get around to putting the rework to code.

**Comment by jacogr** [comment]
Closing.
