### ISSUE TITLE
Remove node-gyp

### ISSUE THREAD

**Issue by Swader** [polkadot-js/common#731]
Node-gyp causes many headaches on many environments, needlessly bloating the compile size and stack people need to install. For this reason, a JS-native crypto lib was funded (and audited) by key players in the Ethereum ecosystem, resulting in [ethereum-cryptography](https://github.com/ethereum/js-ethereum-cryptography). 

Because the only dependency that needs node-gyp in Polkadot JS API is secp256k1 and this now exists [here](https://github.com/ethereum/js-ethereum-cryptography#secp256k1-submodule), I propose we remove all use of node-gyp in favor of these new libs.

**Comment by jacogr** [comment]
I did drop secp256k1 for pure elliptic since they changed the API and elliptic was needed anyway elsewhere, so that killed one. However atm `browserify-aes` has a dep via `parse-asn1` on node-gyp. (That seems like the only pure non-dev dep)

**Comment by jacogr** [comment]
Actually digging a bit while waiting for builds, there is none left here, the last non-dev-dependency went out with the changes to secp. 

There is one left API-wise which actually sits over here https://github.com/polkadot-js/polyfill/blob/master/packages/x-ws/package.json#L28

That is not removable since the WS part needs to support Node, browser and RN.

**Comment by jacogr** [comment]
Closing. Not going to investigate this further, once Node natively supports WS, can revisit. As of now, it stays as-is. Not an issue on the crypto layer.

(Always happy for PRs that can improve edge-cases, i.e. as mentioned "for some users", have not seen reports, so certainly not a priority.)
