### ISSUE TITLE
Add verify for ethereum signatures

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/common#759]
Like for ed25519 and sr25519, we need a verify function for ethereum in the crypto-util lib.

This would be used in `packages/page-signing/src/Verify.tsx`

What do you think @jacogr ?

**Comment by jacogr** [comment]
Sure, makes sense. PRs welcome.

**Comment by jacogr** [comment]
It should actually be there/available, since the pair can do verification. https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/signature/verify.ts#L27

The tricky bit there comes if with the `isExpanded` param (which is true for expanded publicKeys like on a pair). Not sure if it works with an address itself with unexpanded. So there may be a hole left.
