### ISSUE TITLE
Does polkadot's library support PCX?

### ISSUE THREAD

**Issue by Wangmmx** [polkadot-js/common#776]
I found a commit that Polkadot’s new configuration supports PCX’s decimal and prefix information. Does it also support PCX for assembly transactions and offline signatures? PCX2.0 will be launched soon. The offline signature part is not clear, so I want to try Polkadot’s lib. Looking forward to your reply！Thanks!

**Comment by jacogr** [comment]
Which commit are you referring to?

The libs will generally try and support all the features Polkadot/Substrate has in the base layer to ensure that transactions can be handled correctly. As of now, there has been no additions for any new formats.

**Comment by Wangmmx** [comment]
> Which commit are you referring to?
> 
> The libs will generally try and support all the features Polkadot/Substrate has in the base layer to ensure that transactions can be handled correctly. As of now, there has been no additions for any new formats.

https://github.com/polkadot-js/common/issues/776#issuecomment-732022860
I found there are some configurations of chainX that have been added here. Is this only the part that supports chrome expansion?

**Comment by jacogr** [comment]
Sorry, the comment you made links to this issue, so cannot quite see what you are referring to :) Cut and paste mistake?

**Comment by Wangmmx** [comment]
https://github.com/polkadot-js/common/commit/b22f5643a92d50c7c0dff3660d8ea8d7e51f90f6
Sorry for my mistake

**Comment by jacogr** [comment]
Ahh, ok, so that is just a mapping to the general ss58 formats that are in the Substrate codebase. So basically all those are known and will be used anywhere ss58 is referred to. If ChainX is a standard Substrate implementation with regards to signing, the API and utils would work. 

(I've seen they have asked about the use in the extension, so I'm assuming they do follow the same approach as base Substrate. The list you linked to is used in the extension as known chains, so at the next release will also show by default)

**Comment by jacogr** [comment]
Closing.
