### ISSUE TITLE
Can not use BN_ZERO defined in @polkadot/util

### ISSUE THREAD

**Issue by tolak** [polkadot-js/common#812]
Hi, i got an error thrown by polkadot/api  when compling it. The error is:

```sh
Can't import the named export 'BN_ZERO' from non EcmaScript module (only default export is available)
```

Looks like we try to use BN_ZERO defined in polkadot/util/BN/const module but it maybe not being exported properly

```sh
import { assert, BN_ZERO, logger, u8aEq, u8aToU8a } from 'polkadot/util';
```

 - polkadot/util ^5.0.1
 - polkadot/api ^3.0.1

I'm not very familiar with the JS code that you guys export this const variable, may be you can help me out.

**Comment by jacogr** [comment]
When you say “when compiling it” which environment are you using? Basically it is Webpack, Babel, TypeScript. ...?

**Comment by tolak** [comment]
TypeScript it is. Full project is forked from [here](https://github.com/substrate-developer-hub/substrate-front-end-template/tree/v2.0.0) and polkadot packages have been  updated to above version

**Comment by jacogr** [comment]
So steps to reproduce would be -

- fork the above project
- update deps
- yarn build?

**Comment by jacogr** [comment]
This seems to be a known issue with `create-react-app` as used by that project. The issue is that it tries to use esm modules by default, however doesn't know that `.mjs` files are actual esm modules, failing when it actually uses import/export.

A solution (linking to a similar GH issue) is found here - https://stackoverflow.com/questions/64002604/how-to-make-create-react-app-support-mjs-files-with-webpack

**Comment by jacogr** [comment]
Verified it fixes the CRA resolution where it includes `.mjs` but doesn't use them correctly. My steps as per the link -

1. `yarn add react-app-rewired --dev`
2. Change `package.json` to use `react-app-rewired`, e.g. instead of `"build": "react-scripts build"` used  `"build": "react-app-rewired build"`
3. Added a root `config-overrides.js` with the following contents -

```js
module.exports = function override(webpackConfig) {
  webpackConfig.module.rules.push({
    test: /\.mjs$/,
    include: /node_modules/,
    type: "javascript/auto"
  });

  return webpackConfig;
}
```

I see react-scripts 4.0.1 is out, however not sure if they fixed this. They still seem to use `.mjs` as an allowed extension everywhere in the config, but the above loader-override is not there. (So support seem like it allows the .mjs esm files, but doesn't know how to treat them 100%)

**Comment by tolak** [comment]
This solved that problem, many thanks!

**Comment by jimmychu0807** [comment]
I thank you for you guys investigating this issue 🙏
