### ISSUE TITLE
Rococo-v1: SS58Prefix > 63 ---> UnknownVersion error

### ISSUE THREAD

**Issue by sea212** [polkadot-js/common#962]
**Issue**
If [SS58Prefix](https://github.com/paritytech/polkadot/blob/4758b9f6a3625b0a8cc6457373bba47f4003739e/runtime/polkadot/src/lib.rs#L151) is greater than 63, all extrinsics that are submitted (using [polkadot.js.org/apps](https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/extrinsics)) lead to the following error:

> -32602: Invalid params: UnknownVersion.

**System**
OS: # 56~20.04.1-Ubuntu - Kernel 5.8.0-50-generic  - x86_64 GNU/Linux
CPU: Ryzen 5 3600
RAM: 32 GB - 2x D416GB 3600-17 Viper Steel - 0B swap
Browser: Firefox 88.0 (64-bit)

**Test environment**
-  [Polkadot from rococo-v1 branch](https://github.com/paritytech/substrate/tree/2be8fcc4236d32786c62f6f27a98e7fe7e550807)
- Built and ran with: `cargo build && RUST_LOG=runtime=debug ./target/debug/polkadot --dev --tmp` 
  - rustc 1.52.0-nightly (3a5d45f68 2021-03-09)
  - cargo 1.52.0-nightly (970bc67c3 2021-03-07)
- Tested with [polkadot.js.org/apps](https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/extrinsics) (any extrinsic, for example transfer of currency from ALICE to BOB) - failure
- Tested with [substrate-api-client](https://github.com/scs/substrate-api-client) - success

**Logs: polkadot.js.org/apps**
When sending an extrinsic, the console delivers the following output:
> 2021-04-29 20:55:42        RPC-CORE: accountNextIndex(accountId: AccountId): Index:: -32602: Invalid params: UnknownVersion. polkadot.02.41f91f81.js:1:205810

> signAndSend: error: Error: -32602: Invalid params: UnknownVersion.

**Comment by jacogr** [comment]
Tested this with the Subsocial and other prefixes on recent Substrate master as well as Rococo relay form the apps UI as well, querying and transacting. No issues.

**Comment by jacogr** [comment]
So, what I can see hapenning on the Rust side -

1. When the prefix is in the ss58 registry, all ok, e.g. 252 works perfectly - https://github.com/paritytech/substrate/blob/master/ss58-registry.json
2. When the prefix is not in there, e.g. 251, it fails to work. (`UnknownVersion` would make sense in this case, since it is not a registered version)

**Comment by sea212** [comment]
Thanks a lot for investigating into this @jacogr .
Are there any advantages in performing these checks and especially in completely denying the interaction with the network in case the prefix is not registered?
In preparation of the upcoming inclusion into the list the prefix was changed, which lead to this error and completely denied interaction with the chain. A revert to the default prefix was necessary until the inclusion into the list will have been performed.
I would prefer if the user could decide how to handle this. For example, when this scenario is detected, warn the user that this prefix is not known and let the user decide whether to continue (with the option to memorize this selection) or to abort.

**Comment by jacogr** [comment]
You would need to refer the "how the node handles it" implementation questions to the Substrate repo. 

I do believe it makes 100% sense being strict otherwise the registry is not performing the function designated to it. (On the Js side it is still "lax", but slightly harder to properly firm-up since the knowledge always lags the upstream registry)
